name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Install tox
      run: pip3 install tox
    - name: Render Documentation
      run: tox -e py3-html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref_name == 'main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/html
