name: Check External Links

on:
  pull_request:

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Clone repo
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install python3-pip tox -y
          pip3 install -r requirements/setup.txt
    - name: Check External Links
      run: tox -e py3-linkcheck
