name: Check External Links

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    - name: Install dependencies
      run: pip3 install -r requirements/setup.txt
    - name: Check External Links
      run: tox -e py3-linkcheck
