name: Release
# Build a release and attach the generated PDF as GitHub asset.
# The release tag should be in the following format: imx8mx-pd23.1.0
#
# This action generates a draft release with generated pdfs for all platforms
# and versions. The release has to be converted to a final release manually via
# GitHub:
# - remove not required PDF files
# - convert to final release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Clone repo with all tags (required for git describe)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install tox texlive-latex-extra texlive-xetex texlive-lang-chinese latexmk python3-pip -y
          pip3 install -r requirements/setup.txt

    - name: Build PDF Documentation
      run: |
        tox -e intl
        tox -e pdf

      ######## CREATE RELEASE and UPLOAD BUILD ARTIFACTS ########
    - name: Extract tag name
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: true
        prerelease: false
        name: ${{ env.TAG_NAME }}
        files: build/latex/en/*.pdf
