name: Spelling Check

on:
  pull_request:

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Initialize Problem Matcher
      uses: codespell-project/codespell-problem-matcher@v1
    - name: Check Spelling
      uses: codespell-project/actions-codespell@v1
      with:
        ignore_words_file: .codespellignore
        check_filenames: true
        path: source
